### ISSUE TITLE
[NestedList] It is hard to click on elements with short names in nested list

### ISSUE THREAD

**Issue by jecisc** [DuneSt/MaterialDesignLite#100]
To correct we need to add this CSS property:

```CSS
.nestedList .expList li .item {
    flex-grow: 1;
}
```
